### ISSUE TITLE
Help in installation

### ISSUE THREAD

**Issue by Nomad-of-Ouroboros** [paulbricman/conceptarium#6]
Hi, I'm someone from a non-coding background so I have some difficulties following the instructions in the installation guide. Can you elaborate more on the installation guide (a step-by-step installation procedure would be great) in readme so that individuals from non-technical backgrounds can also make use of this wonderful resource.  

Additionally can you explain how I can self-host this application using a salvaged desktop?

**Comment by paulbricman** [comment]
Thanks for the interest! I think the easiest way to get it up and running is to:
1. Install Docker on the host, following the instructions on the [Docker website](https://docs.docker.com/engine/install/), or just Googling your way through. Docker is a utility which knows how to run self-contained environments (i.e. a bundle of an operating system, some requirements, and the conceptarium) so that you don't have to worry about recreating that environment manually. You just run this predefined image which contains everything necessary in a sort of sandbox.
2. Run the conceptarium using `docker run -p 8000:8000 paulbricman/conceptarium ` in your terminal/console/command line. After seeing that there's no such conceptarium bundle on your host, it will fetch it from the internet first. There might also be a way of doing this through the GUI on Docker Desktop, though I'm not familiar with it.

The good news is that I have plans for hosting all conceptarium-related tools (ideoscope, the upcoming lexiscore, and future ones, though not the conceptarium itself) for free on the internet so that you don't have to also install them locally if you don't want to. You'd just go to a public URL and enter the URL of your conceptarium, but for the conceptarium itself I haven't come up with a free way of hosting such a service.

Hope this helps and let me know if you run into any other issues!

**Comment by Nomad-of-Ouroboros** [comment]
Yes, it was helpful. Thanks. This also made me curious about what type of tool the conceptarium is (specifically whether it is an application like Obsidian or Notion) and where the data gets stored?

**Comment by paulbricman** [comment]
Good questions all of them, @Nomad-of-Ouroboros.

1. The conceptarium is a web server which, when run on a host, serves a few web pages which help you interact with it. This means that if configured properly, you can access your conceptarium from any device with a browser. I mainly access mine from my laptop while at home and from my phone while on the go.
2. The data is stored locally on the host where the web server is being run.
3. Deploying the conceptarium on a salvaged desktop might actually be a good idea, because if configured properly, you can access it from anywhere in the world, just as a normal website.
4. Yes, through its address.

A couple more notes. In order to make it possible to access the conceptarium from anywhere in the world after running the docker thing, you have to do one more thing: running [ngrok[(https://ngrok.com/), as mentioned in the README. This utility creates a tunnel from your computer to the broader internet through a website address which it generates randomly for you, and you just use that on your devices.

I think some screenshots of the webpages both from desktop and mobile can be found in the screencasts here: https://paulbricman.com/reflections/early-conceptarium-workflows.

Thanks again for the interest and let me know if you run into further issues.

**Comment by Nomad-of-Ouroboros** [comment]
Hi again @paulbricman, I finally got the chance to install the application and I reached this stage. How do I proceed? 
![image](https://user-images.githubusercontent.com/94626946/145275989-e31d3298-3183-4815-a6c1-d2d7b1b41074.png)
![image](https://user-images.githubusercontent.com/94626946/145277501-6467519d-7ad5-4637-893f-eb15425d3cef.png)

**Comment by paulbricman** [comment]
Congrats, you're so close! 

Try a few of the following:
- 127.0.0.1:8000/find/lang/form
- 127.0.0.1:8000/save/lang/form
- 127.0.0.1:8000/find/imag/form
- 127.0.0.1:8000/save/imag/form
- 127.0.0.1:8000/docs (for a list of every path)

**Comment by paulbricman** [comment]
New installation now with the rework, so closing this.
